### ISSUE TITLE
Cryptic pw.x error with BEEF-vdW enabled

### ISSUE THREAD

**Issue by ajmedford** [vossjo/ase-espresso#19]
I am trying to get ASE/ESPRESSO/BEEF up and running on the GT PACE cluster. I have successfully built the 5.1.r11289-pybeef version based on the instructions and configured the ASE interface which seems to work fine with PBE. However, when I try to run a BEEF-vdW calculation I get the error message appended below. I have successfully run the PW/examples/vdwDF_example in the espresso build so I am reasonably confident that the issue is not in the vdW calculation. Any ideas?

```forrtl: severe (168): Program Exception - illegal instruction
Image              PC                Routine            Line        Source             
pw.x               0000000000B62C51  Unknown               Unknown  Unknown
pw.x               0000000000B613A7  Unknown               Unknown  Unknown
pw.x               0000000000AFEEE4  Unknown               Unknown  Unknown
pw.x               0000000000AFECF6  Unknown               Unknown  Unknown
pw.x               0000000000A907FF  Unknown               Unknown  Unknown
pw.x               0000000000A973B1  Unknown               Unknown  Unknown
libpthread.so.0    000000328DE0F7E0  Unknown               Unknown  Unknown
pw.x               0000000000A800BD  Unknown               Unknown  Unknown
pw.x               00000000007BFFD6  funct_mp_gcxc_           1601  funct.f90
pw.x               00000000004D4B21  gradcorr_                 127  gradcorr.f90
pw.x               00000000005F875C  v_of_rho_                 514  v_of_rho.f90
pw.x               0000000000578979  potinit_                  222  potinit.f90
pw.x               00000000004E0D59  init_run_                  99  init_run.f90
pw.x               000000000040C243  run_pwscf_                 72  run_pwscf.f90
pw.x               000000000040C100  MAIN__                     30  pwscf.f90
pw.x               000000000040C07E  Unknown               Unknown  Unknown
libc.so.6          000000328D61ED5D  Unknown               Unknown  Unknown
pw.x               000000000040BF89  Unknown               Unknown  Unknown
Traceback (most recent call last):
  File "ase_espresso_test.py", line 12, in <module>
    print a.get_potential_energy()
  File "/nv/hp22/amedford6/medford-shared/INSTALL/lib/python2.7/site-packages/ase/atoms.py", line 676, in get_potential_energy
    energy = self._calc.get_potential_energy(self)
  File "/nv/hp22/amedford6/medford-shared/INSTALL/lib/python2.7/site-packages/espresso/__init__.py", line 1958, in get_potential_energy
    self.update(atoms)
  File "/nv/hp22/amedford6/medford-shared/INSTALL/lib/python2.7/site-packages/espresso/__init__.py", line 1407, in update
    self.read(atoms)
  File "/nv/hp22/amedford6/medford-shared/INSTALL/lib/python2.7/site-packages/espresso/__init__.py", line 1523, in read
    raise RuntimeError, 'SCF calculation failed'
RuntimeError: SCF calculation failed```

**Comment by lmmentel** [comment]
Could you paste the error that you get in the QE log file?

**Comment by ajmedford** [comment]
Sure... it doesn't look like there is an error though:

```
  python dir          : /nv/hp22/amedford6/medford-shared/INSTALL/lib/python2.7/site-packages/espresso
  espresso dir        : /nv/hp22/amedford6/medford-shared/builds/espresso/5.1.r11289-pybeef/intel-15.0+mvapich2-2.1+mkl-11.2/espresso-5.1.r11289-pybeef/bin
  pseudo dir          : /nv/hp22/amedford6/medford-shared/data/pseudos/SSSP_eff_PBE
  ase-espresso py git : c91b4c2-git



     Program PWSCF v.5.1rc2 starts on 18Feb2017 at 14:46:30 

     This program is part of the open-source Quantum ESPRESSO suite
     for quantum simulation of materials; please cite
         "P. Giannozzi et al., J. Phys.:Condens. Matter 21 395502 (2009);
          URL http://www.quantum-espresso.org", 
     in publications or presentations arising from this work. More details at
     http://www.quantum-espresso.org/quote

     Parallel version (MPI), running on     1 processors
     Reading input from pw.inp
     Message from routine read_cards :
     DEPRECATED: no units specified in CELL_PARAMETERS card

     Current dimensions of program PWSCF are:
     Max number of different atomic species (ntypx) = 10
     Max number of k-points (npk) =  40000
     Max angular momentum in pseudopotentials (lmaxx) =  3

     **************************************************************************
     Initializing libbeef V0.1.1 with the BEEF-vdW functional.
     Citation: Wellendorff et al., PRB 85, 235149 (2012).
     **************************************************************************


     IMPORTANT: XC functional enforced from input :
     Exchange-correlation      = BEEF-VDW ( 1  4 27 13 2)
     Any further DFT definition will be discarded
     Please, verify this is what you really want


     Subspace diagonalization in iterative solution of the eigenvalue problem:
     a serial algorithm will be used

 
     G-vector sticks info
     --------------------
     sticks:   dense  smooth     PW     G-vecs:    dense   smooth      PW
     Sum         517     211     85                 7991     2085     459
 


     bravais-lattice index     =            0
     lattice parameter (alat)  =       1.8897  a.u.
     unit-cell volume          =     115.0293 (a.u.)^3
     number of atoms/cell      =            1
     number of atomic types    =            1
     number of electrons       =        19.00
     number of Kohn-Sham states=           19
     kinetic-energy cutoff     =      25.7245  Ry
     charge density cutoff     =     257.2453  Ry
     convergence threshold     =      7.3E-08
     mixing beta               =       0.7000
     number of iterations used =            8  plain     mixing
     Exchange-correlation      = BEEF-VDW ( 1  4 27 13 2)
     nstep                     =           50


     celldm(1)=   1.889726  celldm(2)=   0.000000  celldm(3)=   0.000000
     celldm(4)=   0.000000  celldm(5)=   0.000000  celldm(6)=   0.000000

     crystal axes: (cart. coord. in units of alat)
               a(1) = (   0.000000   2.042650   2.042650 )  
               a(2) = (   2.042650   0.000000   2.042650 )  
               a(3) = (   2.042650   2.042650   0.000000 )  

     reciprocal axes: (cart. coord. in units 2 pi/alat)
               b(1) = ( -0.244780  0.244780  0.244780 )  
               b(2) = (  0.244780 -0.244780  0.244780 )  
               b(3) = (  0.244780  0.244780 -0.244780 )  


     PseudoPot. # 1 for Ag read from file:
     /nv/hp22/amedford6/medford-shared/data/pseudos/SSSP_eff_PBE/Ag.UPF
     MD5 check sum: d66d668201baa78d5eb5b04ef7011058
     Pseudo is Ultrasoft + core correction, Zval = 19.0
     Generated by new atomic code, or converted to UPF format
     Using radial grid of  887 points,  6 beta functions with: 
                l(1) =   0
                l(2) =   0
                l(3) =   1
                l(4) =   1
                l(5) =   2
                l(6) =   2
     Q(r) pseudized with  6 coefficients,  rinner =    1.300   1.300   1.300
                                                       1.300   1.300

     vdW kernel table read from file vdW_kernel_table
     MD5 check sum: 88c60d17101ec99b63477f765c8de84d

     atomic species   valence    mass     pseudopotential
        Ag1           19.00   107.86800     Ag( 1.00)

     48 Sym. Ops., with inversion, found



   Cartesian axes

     site n.     atom                  positions (alat units)
         1           Ag1 tau(   1) = (   0.0000000   0.0000000   0.0000000  )

     number of k points=    72  Fermi-Dirac smearing, width (Ry)=  0.0073
                       cart. coord. in units 2pi/alat
        k(    1) = (   0.0000000   0.0000000   0.0000000), wk =   0.0011574
        k(    2) = (   0.0203983   0.0203983  -0.0203983), wk =   0.0092593
        k(    3) = (   0.0407967   0.0407967  -0.0407967), wk =   0.0092593
        k(    4) = (   0.0611950   0.0611950  -0.0611950), wk =   0.0092593
        k(    5) = (   0.0815934   0.0815934  -0.0815934), wk =   0.0092593
        k(    6) = (   0.1019917   0.1019917  -0.1019917), wk =   0.0092593
        k(    7) = (  -0.1223900  -0.1223900   0.1223900), wk =   0.0046296
        k(    8) = (   0.0407967   0.0000000   0.0000000), wk =   0.0069444
        k(    9) = (   0.0611950   0.0203983  -0.0203983), wk =   0.0277778
        k(   10) = (   0.0815934   0.0407967  -0.0407967), wk =   0.0277778
        k(   11) = (   0.1019917   0.0611950  -0.0611950), wk =   0.0277778
        k(   12) = (   0.1223900   0.0815934  -0.0815934), wk =   0.0277778
        k(   13) = (  -0.1019917  -0.1427884   0.1427884), wk =   0.0277778
        k(   14) = (  -0.0815934  -0.1223900   0.1223900), wk =   0.0277778
        k(   15) = (  -0.0611950  -0.1019917   0.1019917), wk =   0.0277778
        k(   16) = (  -0.0407967  -0.0815934   0.0815934), wk =   0.0277778
        k(   17) = (  -0.0203983  -0.0611950   0.0611950), wk =   0.0277778
        k(   18) = (  -0.0000000  -0.0407967   0.0407967), wk =   0.0138889
        k(   19) = (   0.0815934   0.0000000   0.0000000), wk =   0.0069444
        k(   20) = (   0.1019917   0.0203983  -0.0203983), wk =   0.0277778
        k(   21) = (   0.1223900   0.0407967  -0.0407967), wk =   0.0277778
        k(   22) = (   0.1427884   0.0611950  -0.0611950), wk =   0.0277778
        k(   23) = (  -0.0815934  -0.1631867   0.1631867), wk =   0.0277778
        k(   24) = (  -0.0611950  -0.1427884   0.1427884), wk =   0.0277778
        k(   25) = (  -0.0407967  -0.1223900   0.1223900), wk =   0.0277778
        k(   26) = (  -0.0203983  -0.1019917   0.1019917), wk =   0.0277778
        k(   27) = (   0.0000000  -0.0815934   0.0815934), wk =   0.0138889
        k(   28) = (   0.1223900   0.0000000   0.0000000), wk =   0.0069444
        k(   29) = (   0.1427884   0.0203983  -0.0203983), wk =   0.0277778
        k(   30) = (   0.1631867   0.0407967  -0.0407967), wk =   0.0277778
        k(   31) = (  -0.0611950  -0.1835850   0.1835850), wk =   0.0277778
        k(   32) = (  -0.0407967  -0.1631867   0.1631867), wk =   0.0277778
        k(   33) = (  -0.0203983  -0.1427884   0.1427884), wk =   0.0277778
        k(   34) = (   0.0000000  -0.1223900   0.1223900), wk =   0.0138889
        k(   35) = (   0.1631867   0.0000000   0.0000000), wk =   0.0069444
        k(   36) = (   0.1835850   0.0203983  -0.0203983), wk =   0.0277778
        k(   37) = (  -0.0407967  -0.2039834   0.2039834), wk =   0.0277778
        k(   38) = (  -0.0203983  -0.1835850   0.1835850), wk =   0.0277778
        k(   39) = (  -0.0000000  -0.1631867   0.1631867), wk =   0.0138889
        k(   40) = (   0.2039834   0.0000000   0.0000000), wk =   0.0069444
        k(   41) = (  -0.0203983  -0.2243817   0.2243817), wk =   0.0277778
        k(   42) = (   0.0000000  -0.2039834   0.2039834), wk =   0.0138889
        k(   43) = (  -0.2447801   0.0000000   0.0000000), wk =   0.0034722
        k(   44) = (   0.0815934   0.0407967   0.0000000), wk =   0.0277778
        k(   45) = (   0.1019917   0.0611950  -0.0203983), wk =   0.0555556
        k(   46) = (   0.1223900   0.0815934  -0.0407967), wk =   0.0555556
        k(   47) = (  -0.1019917  -0.1427884   0.1835850), wk =   0.0555556
        k(   48) = (  -0.0815934  -0.1223900   0.1631867), wk =   0.0277778
        k(   49) = (   0.1223900   0.0407967   0.0000000), wk =   0.0277778
        k(   50) = (   0.1427884   0.0611950  -0.0203983), wk =   0.0555556
        k(   51) = (  -0.0815934  -0.1631867   0.2039834), wk =   0.0555556
        k(   52) = (  -0.0611950  -0.1427884   0.1835850), wk =   0.0555556
        k(   53) = (  -0.0407967  -0.1223900   0.1631867), wk =   0.0555556
        k(   54) = (  -0.0203983  -0.1019917   0.1427884), wk =   0.0555556
        k(   55) = (   0.0000000  -0.0815934   0.1223900), wk =   0.0277778
        k(   56) = (   0.1631867   0.0407967  -0.0000000), wk =   0.0277778
        k(   57) = (  -0.0611950  -0.1835850   0.2243817), wk =   0.0555556
        k(   58) = (  -0.0407967  -0.1631867   0.2039834), wk =   0.0555556
        k(   59) = (  -0.0203983  -0.1427884   0.1835850), wk =   0.0555556
        k(   60) = (   0.0000000  -0.1223900   0.1631867), wk =   0.0277778
        k(   61) = (  -0.0407967  -0.2039834   0.2447801), wk =   0.0277778
        k(   62) = (  -0.0203983  -0.1835850   0.2243817), wk =   0.0555556
        k(   63) = (   0.0000000  -0.1631867   0.2039834), wk =   0.0277778
        k(   64) = (  -0.2447801   0.0407967  -0.0000000), wk =   0.0138889
        k(   65) = (  -0.0815934  -0.1631867   0.2447801), wk =   0.0277778
        k(   66) = (  -0.0611950  -0.1427884   0.2243817), wk =   0.0555556
        k(   67) = (  -0.0407967  -0.1223900   0.2039834), wk =   0.0277778
        k(   68) = (  -0.0407967  -0.1631867   0.2447801), wk =   0.0277778
        k(   69) = (  -0.0203983  -0.1427884   0.2243817), wk =   0.0555556
        k(   70) = (   0.0000000  -0.1223900   0.2039834), wk =   0.0277778
        k(   71) = (  -0.2447801   0.0815934   0.0000000), wk =   0.0138889
        k(   72) = (  -0.2447801   0.1223900   0.0000000), wk =   0.0069444

     Dense  grid:     7991 G-vectors     FFT dimensions: (  27,  27,  27)

     Smooth grid:     2085 G-vectors     FFT dimensions: (  18,  18,  18)

     Largest allocated arrays     est. size (Mb)     dimensions
        Kohn-Sham Wavefunctions         0.08 Mb     (     268,   19)
        NL pseudopotentials             0.07 Mb     (     268,   18)
        Each V/rho on FFT grid          0.30 Mb     (   19683)
        Each G-vector array             0.06 Mb     (    7991)
        G-vector shells                 0.00 Mb     (     132)
     Largest temporary arrays     est. size (Mb)     dimensions
        Auxiliary wavefunctions         0.31 Mb     (     268,   76)
        Each subspace H/S matrix        0.09 Mb     (      76,   76)
        Each <psi_i|beta_j> matrix      0.01 Mb     (      18,   19)
        Arrays for rho mixing           2.40 Mb     (   19683,    8)

     Initial potential from superposition of free atoms

     starting charge   18.49995, renormalised to   19.00000
```

**Comment by ajmedford** [comment]
For the record, the pw.inp file is:

```
&CONTROL
  calculation='relax',
  prefix='calc',
  pseudo_dir='/nv/hp22/amedford6/medford-shared/data/pseudos/SSSP_eff_PBE',
  outdir='.',
  tprnfor=.true.,
/
&SYSTEM
  ibrav=0,
  celldm(1)=1.8897261245650618d0,
  nat=1,
  ntyp=1,
  ecutwfc=25.7245266536d0,
  ecutrho=257.245266536d0,
  nbnd=19,
  occupations='smearing',
  smearing='fd',
  degauss=0.00734986475817d0,
  input_dft='BEEF-vdW',
/
&ELECTRONS
  diagonalization='david',
  conv_thr=7.34986475817e-08,
  mixing_beta=0.7d0,
  electron_maxstep=100,
  conv_thr=7.34986475817e-08,
/
&IONS
  ion_dynamics='ase3',
/
CELL_PARAMETERS
    0.000000000000000d0     2.042650000000000d0     2.042650000000000d0
    2.042650000000000d0     0.000000000000000d0     2.042650000000000d0
    2.042650000000000d0     2.042650000000000d0     0.000000000000000d0
ATOMIC_SPECIES
Ag1 107.868d0 Ag.UPF
ATOMIC_POSITIONS {crystal}
Ag1      0.000000000000000d0     0.000000000000000d0    -0.000000000000000d0
K_POINTS automatic
12 12 12 0 0 0
```

**Comment by ajmedford** [comment]
The previous errors occur with the Intel 15.0 compiler, but if I compile with Intel 16.0 then there are no errors. I am closing the issue since it now seems to be working fine, but it might be worth mentioning somewhere which version of the compiler is used for testing. For future reference I got a successful build with Intel 16.0 compiler, mvapich2 2.2, and mkl 11.3.
